### ISSUE TITLE
set up publishing to npm

### ISSUE THREAD

**Issue by Pixelik** [peopledoc/html-linter#33]
set each new release to automatically publish to npm

**Comment by Pixelik** [comment]
from Slack (@GreatWizard) :  

> create personnal npm account
>publish stuff under this account
> and then link the package to the PD organisation
> so everyone from the organisation can publish new versions

**Comment by saintsebastian** [comment]
https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by Pixelik** [comment]
I suggest we rename **layout-linter** (at least inside package.json) to **html-linter**.

The [name is important](https://docs.npmjs.com/getting-started/publishing-npm-packages#choose-a-name) when it comes to users looking for a package on npmjs and I think html-linter is better in that case.

@peopledoc/tribe-js what do you think ?

**Comment by Pixelik** [comment]
@xcambar are you ok with renaming the repo and the module to **html-linter** ?
once this is sorted I will go ahead and publish to npmjs.com

**Comment by xcambar** [comment]
Go ahead 🤘
